#!/bin/sh

# wallpaper
~/.fehbg &

# xresources
xrdb ~/.Xresources

# composer
picom --experimental-backends -b 

# configure bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config normal_border_width 0
bspc config window_gap 20
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0 
bspc config left_padding 0

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a thunar state=floating follow=on
